// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Autor(a)    : Henrique Brandão
// Data atual  : 18/03/2024
Algoritmo "Numeros_Divisiveis_Por_4"
// Autor: [Seu Nome]
// Data atual: [Data atual]

Var
    numero: Inteiro

Inicio
    Para numero de 1 ate 199 faca
        Se numero mod 4 = 0 entao
            Escreva numero
        FimSe
    FimPara
Fim
