// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Autor(a)    : Henrique Brandão
// Data atual  : 18/03/2024
Algoritmo "Soma_Cem_Primeiros_Numeros"
// Autor: [Seu Nome]
// Data atual: [Data atual]

Var
    soma, numero: Inteiro

Inicio
    soma <- 0

    Para numero de 1 ate 100 faca
        soma <- soma + numero
    FimPara

    Escreva "O total da soma dos cem primeiros números inteiros é: ", soma
Fim
