// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Autor(a)    : Henrique Brandão
// Data atual  : 18/03/2024
Algoritmo "Quadrados_De_15_A_200"
// Autor: [Seu Nome]
// Data atual: [Data atual]

Var
    numero, quadrado: Inteiro

Inicio
    Para numero de 15 ate 200 faca
        quadrado <- numero * numero
        Escreva "O quadrado de ", numero, " é: ", quadrado
    FimPara
Fim
