// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Autor(a)    : Henrique Brandão
// Data atual  : 18/03/2024
Algoritmo "Quadrado_Diferenca_A_B"
// Autor: [Seu Nome]
// Data atual: [Data atual]

Var
    A, B, resultado: Inteiro

Inicio
    Escreva "Digite o valor de A: "
    Leia A
    Escreva "Digite o valor de B: "
    Leia B

    resultado <- (A - B)^2

    Escreva "O quadrado da diferença entre A e B é: ", resultado
Fim
